[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd generated && npm install --legacy-peer-deps && cd .. && npm run codegen"

[deploy]
startCommand = "npm start"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

